version: "3"
services:
  #Laravel App
  sikma:
    build:
      context: .
      dockerfile: Dockerfile
    image: dhimasarbi/sikma
    container_name: sikma
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: sikma
      SERVICE_TAGS: sikma
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-sikma
  #Nginx Service
  nginx-sikma:
    image: nginx:alpine
    container_name: nginx-sikma
    restart: unless-stopped
    tty: true
    ports:
      - "8090:8090"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-sikma

#Docker Networks
networks:
  laravel-sikma:
    driver: bridge
